export const PAKISTANI_CITIES = [
  'Lahore',
  'Karachi',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Gujranwala',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Bahawalpur',
  'Sargodha',
  'Hyderabad',
  'Abbottabad',
  'Murree',
  'Gujrat',
  'Sheikhupura',
  'Jhang',
  'Rahim Yar Khan',
  'Sahiwal',
] as const;

export type PakistaniCity = (typeof PAKISTANI_CITIES)[number];

export const LAHORE_AREAS = [
  'DHA Phase 1',
  'DHA Phase 2',
  'DHA Phase 3',
  'DHA Phase 4',
  'DHA Phase 5',
  'DHA Phase 6',
  'DHA Phase 7',
  'DHA Phase 8',
  'DHA Phase 9',
  'Bahria Town',
  'Johar Town',
  'Gulberg',
  'Model Town',
  'Garden Town',
  'Wapda Town',
  'Lake City',
  'Valencia',
  'Cantt',
  'Iqbal Town',
  'Township',
];

export const ISLAMABAD_AREAS = [
  'F-6',
  'F-7',
  'F-8',
  'F-10',
  'F-11',
  'G-9',
  'G-10',
  'G-11',
  'G-13',
  'I-8',
  'I-10',
  'E-7',
  'E-11',
  'DHA Phase 1',
  'DHA Phase 2',
  'Bahria Town',
  'Blue Area',
  'Bani Gala',
];
